title: Art Information Commons
description: [add a blurb about art information commons and this page]

url: https://artinformationcommons.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: About
    url: /about
  - title: Who We Are
    url: /who-we-are
  - title: Updates and Activities
    url: /update-activities
  - title: Events
    url: /events
  - title: Resources
    url: /resources
  
  

social:
  github: --
  twitter: --
  facebook: --
  email: Juliet.Vinegra@philamuseum.org

google_analytics: "UA-58263416-1"
